version: '3.3'

services:
  redis:
    image: redis:alpine
    ports:
        - 6379:6379

  feely:
    build: .
    volumes:
      - "./:/usr/src/app"
    ports:
      - 4000:3000
    links:
      - redis
    environment:
      - REDIS_URL
      - DISCORD_TOKEN
